name: Portfolio Optimizer
description: This AMP will get your financial portfolio from the alpaca API and then use several api calls to LLMs and vectorization to generate reccomendations based on the most relevant news headlines for your portfolio.
author: Team NYU
specification_version: 1.0
prototype_version: 1.0
date: "2024-10-09"


runtimes:
  - editor: Workbench ## Other acceptable values are determined by the runtimes available in your CML environment
    kernel: Python 3.10 ## Same here, check your runtimes (custom runtimes can be added as well)
    edition: Standard ## Particularly relevant if using GPUs, Nvidia GPU

## Below are some sample tasks based on some of the most popular aspects of AMP creation.
tasks:

  ## SESSION related AMP snippet
  - type: run_session
    name: Install Dependencies
    script: 0_session-install-dependencies/install-dependencies.py
    short_summary: Install Requirements and Dependencies
    kernel: python3
    cpu: 2
    memory: 4

  ## JOB related AMP snippet
  - type: create_job
    name: Sample Job
    entity_label: headline_job
    script: data_engineering/get_latest_headlines_job.py
    arguments: --run_job
    cpu: 2
    memory: 4
    short_summary: Create job to get latest headlines.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: headline_job
    short_summary: gets the recent headlines

  ## APPLICATION related AMP snippet
  - type: start_application
    name: Portfolio Optimizer
    short_summary: Launches Portfolio Optimizer
    long_summary: Launches the application and allows the user to ask for portfolio optimization reccommendations from a tailored LLM based on the recent headline news and their own portfolio. 
    subdomain: portfolio-optimization
    script: app_run/app.py
    environment_variables:
      TASK_TYPE: START_APPLICATION